### ISSUE TITLE
There is a version that works with Mac?

### ISSUE THREAD

**Issue by Decameron16** [arindam-m/pyslapi#12]
**Describe the bug**

**To Reproduce**
3. See error (if any) 'Error Log: ....'

**Expected behavior**

**Screenshots**
[To attach a file to an issue, drag and drop it into the comment box]

**System Info**
 - Operating System: [e.g. Windows 10]
 - Blender Version [e.g. 2.82a] (Only official releases)
 - SketchUp Version [e.g. 2019]
 - Importer Version [eg. v.0.20.2]

**Additional context**

**Comment by Villafruela** [comment]
i concur.

i tried with blender 2.90.1, 2.83 LTS, 2.8 none worked. The plugin can't be activated.

![Blender_Preferences](https://user-images.githubusercontent.com/16768482/98042398-cef84d80-1e23-11eb-9ee6-63c236369afb.jpg)

**Comment by Shaddy-ElDesouky** [comment]
![image](https://user-images.githubusercontent.com/73293717/99881469-b0b38f80-2c22-11eb-9e59-a646d472e7fc.png)

**Comment by Shaddy-ElDesouky** [comment]
@Decameron16 https://github.com/martijnberger/pyslapi/releases this is the 2.79 release, there is a mac version, also I understood that there is update for 2.8

**Comment by ideoservo** [comment]
Hello, I've build a version for MacOSX here 
https://github.com/ideoservo/pyslapi/releases/tag/0.21.1-OSX
It works only with models which do not have textures.

See this thread https://forums.sketchup.com/t/su-error-serialisation-when-using-sutexturewritetofile-on-macos-2021-sdk/146194/2


Error log in Blender:
Python: Traceback (most recent call last):
  File "/Users/Admin/Library/Application Support/Blender/2.92/scripts/addons/SketchUp_Importer-OSX/__init__.py", line 886, in execute
    context, **keywords)
  File "/Users/Admin/Library/Application Support/Blender/2.92/scripts/addons/SketchUp_Importer-OSX/__init__.py", line 172, in load
    self.write_materials(self.skp_model.materials)
  File "/Users/Admin/Library/Application Support/Blender/2.92/scripts/addons/SketchUp_Importer-OSX/__init__.py", line 343, in write_materials
    tex.write(tmp_name)
  File "sketchup.pyx", line 330, in sketchup.Texture.write
  File "sketchup.pyx", line 62, in sketchup.check_result
RuntimeError: Sketchup library giving unexpected results SU_ERROR_SERIALIZATION

location: <unknown location>:-1

**Comment by u3dreal** [comment]
I'm trying to get to the root here .. letzt hope someone will look at it 

[https://github.com/SketchUp/api-issue-tracker/issues/632](url)

**Comment by arindam-m** [comment]
If the build instructions for macOS (by @ideoservo) have worked, we may close this issue soon.

**Comment by videopilot** [comment]
I'm also able to get the Mac version built or use the Mac releases mentioned here, but getting the same error as @ideoservo above.

@u3dreal I see you made some progress in that thread. Did SUInitialize and SUTerminate solve it? I'm not clear where those go.
