### ISSUE TITLE
Cant import

### ISSUE THREAD

**Issue by andzejsp** [arindam-m/pyslapi#29]
Hello i was trying to import a large  100mb .skp file, im not even sure whats inside it. I kinda know, that its architectual stuff, because it was sent to me from other comapny, but i cant import it to blender using default settings.

```
Traceback (most recent call last):
  File "C:\Users\Andzejs\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 886, in execute
    context, **keywords)
  File "C:\Users\Andzejs\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 185, in load
    self.write_duplicateable_groups()
  File "C:\Users\Andzejs\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 245, in write_duplicateable_groups
    group=group)
  File "C:\Users\Andzejs\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 640, in conponent_def_as_group
    group=group)
  File "C:\Users\Andzejs\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 614, in conponent_def_as_group
    ob.layers = 18 * [False] + [True] + [False]
AttributeError: 'Object' object has no attribute 'layers'

location: <unknown location>:-1

```

I have tried it in blender 2.83, 2.9, 2.91 and it didnt work.

Any help would be welcome.

**Comment by odil24** [comment]
Seems like it 2021 version of model. If so then try to import 2020 3d model

**Comment by andzejsp** [comment]
Thanks for the reply but im using this addon because i dont have shetchup :) and have no way to convert this file. Getting another version of it from source get complicated and time consuming, but thanks.

**Comment by odil24** [comment]
> Thanks for the reply but im using this addon because i dont have shetchup :) and have no way to convert this file. Getting another version of it from source get complicated and time consuming, but thanks.

Another way that you can get into Blender is using pConPlaner (absolutely free software). With this software you can import SKP file and export it as OBJ to Blender.

**Comment by andzejsp** [comment]
Thanks, the app worked like a charm. I  even tried to save the .skp file to older version - 2018 and 2013 and your addon could not import it.
Then i tried to export it to OBJ but it got stuck for hours and generated very heavy obj file that was corrupted because i didnt wait for it to finish.
Then i just used collada (.dae) and it work with all the materials and units were just fine.
