### ISSUE TITLE
Not able to load certain files.

### ISSUE THREAD

**Issue by franMx** [arindam-m/pyslapi#3]
**Describe the bug**
While trying some files, I get sometinmes the following:
`SKP | Importing: G:\todosa4.skp
SKP | Skipping Layers ...
SKP | Parsed in 1.1613 sec.
imb_load_photoshop: The embed colorspace ("") not supported in existent OCIO configuration file. Fallback to system default colorspace ("sRGB").
SKP | Materials imported in 3.7165 sec.
SKP | Component depths analyzed in 0.1030 sec.
Traceback (most recent call last):
  File "C:\Users\rx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\SketchUp_Importer\__init__.py", line 868, in execute
    context, **keywords)
  File "C:\Users\rx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\SketchUp_Importer\__init__.py", line 184, in load
    self.write_duplicateable_groups()
  File "C:\Users\rx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\SketchUp_Importer\__init__.py", line 237, in write_duplicateable_groups
    group = bpy.data.groups.new(name=gname)
AttributeError: 'BlendData' object has no attribute 'groups'

location: <unknown location>:-1`

**To Reproduce**
1. Try to import
2. Errors are shown in console

**Expected behavior**
Have an improted model

**System Info**
 - Operating System: Windows 10
 - Blender Version  2.82
 - SketchUp Version 2019 and version4
 - Importer Version  v.0.20.2

**Additional context**
Originally posted in bledner artist thread: https://blenderartists.org/t/sketchup-importer-ported-for-blender-2-82a/1223412/33

Followed proposed solution, however plugin doesn't load and I get:

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 352, in enable
    mod.__time__ = os.path.getmtime(mod.__file__)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

If I revert file plugin loads again.

**Comment by arindam-m** [comment]
Can you clarify which particular solution you have tried?

**Comment by franMx** [comment]
I tried the file in https://github.com/arindam-m/pyslapi/blob/develop/sketchup_importer/__init__.py

According to the instructions:
`"If you would like to test out these recent changes (without a new compiled/build release) right now, download this raw file from here 2 and replace it with the existing __init__.py within your addons\SketchUp_Importer directory."` (from blender artist post)

**Comment by arindam-m** [comment]
It works as expected here on my system.
Can you show me your entire directory path where you would have replaced the **__init__.py** file with the new one?

It would be something like 
```
C:\Users\<Your_User_Name>\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Sketchup_Importer
```
Also, share your .skp file with me. If it's for commercial use and you don't want to make it public, send it through DM at BlenderArtists forum. And make the file as small as possible (remove as many objects as you can and purge the unused data).

**Comment by franMx** [comment]
I'm attaching a screenshot, __init__.py2 is the old file, just after the screenshot moved it to another location, but the plugin is still not loading. 
![Capture](https://user-images.githubusercontent.com/8523314/83569926-d91bc600-a4ea-11ea-835b-c795e6adf85c.PNG)

Also I DM you at Blender Artists, don't know what specific models do cause the problems, because I was able to import some of them, but one of those actually is causing problems.

**Comment by arindam-m** [comment]
Thanks for confirming the addon PATH. However, the link that you have provided me with, (at BlenderArtists for a sample file to reproduce the issue) doesn't work.

**Comment by dogactoklu** [comment]
I have the same issue. Nothing I did fixed the issue
