### ISSUE TITLE
'Object' object has no attribute 'layers'

### ISSUE THREAD

**Issue by JohnMackYouTube05** [arindam-m/pyslapi#56]
**Describe the bug**
Unable to load Sketchup File

location: <unknown location>:-1
```
I want this to work, but it doesn't!
**Expected behavior**
Blender should put the entire SketchUp scene into view.



**System Info**
 - Operating System: Windows 11
 - Blender Version 2.93 LTS
 - SketchUp Version: 2021
 - Importer Version v0.23

**Additional context**

When I load a .skp file created in a recent version of SketchUp Pro,  I get this message in the output console:
```
SU | Importing: C:\Users\liljm\Documents\PSHS.skp
SU | Write instance definition as group cafe table.001 Material
Python: Traceback (most recent call last):
  File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer\__init__.py", line 982, in execute
    return SceneImporter().set_filename(keywords['filepath']).load(
  File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer\__init__.py", line 261, in load
    self.write_duplicateable_groups()
  File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer\__init__.py", line 328, in write_duplicateable_groups
    self.conponent_def_as_group(comp_def.entities,
  File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer\__init__.py", line 716, in conponent_def_as_group
    self.conponent_def_as_group(
  File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer\__init__.py", line 710, in conponent_def_as_group
    ob.layers = 18 * [False] + [True] + [False]
AttributeError: 'Object' object has no attribute 'layers'

**Comment by odil24** [comment]
> **Describe the bug** Unable to load Sketchup File
> 
> location: :-1
> 
> ```
> I want this to work, but it doesn't!
> **Expected behavior**
> Blender should put the entire SketchUp scene into view.
> 
> 
> 
> **System Info**
>  - Operating System: Windows 11
>  - Blender Version 2.93 LTS
>  - SketchUp Version: 2021
>  - Importer Version v0.23
> 
> **Additional context**
> 
> When I load a .skp file created in a recent version of SketchUp Pro,  I get this message in the output console:
> ```
> 
> SU | Importing: C:\Users\liljm\Documents\PSHS.skp SU | Write instance definition as group cafe table.001 Material Python: Traceback (most recent call last): File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer__init__.py", line 982, in execute return SceneImporter().set_filename(keywords['filepath']).load( File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer__init__.py", line 261, in load self.write_duplicateable_groups() File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer__init__.py", line 328, in write_duplicateable_groups self.conponent_def_as_group(comp_def.entities, File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer__init__.py", line 716, in conponent_def_as_group self.conponent_def_as_group( File "C:\Users\liljm\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SketchUp_Importer__init__.py", line 710, in conponent_def_as_group ob.layers = 18 * [False] + [True] + [False] AttributeError: 'Object' object has no attribute 'layers'

Hi.
Sketchup importer v0.23 works only with Blender 3.0+ and also use this latest version:
https://github.com/arindam-m/pyslapi/issues/55

Note that, install addon as repack and copy/paste to "blender_version/scripts/addons" NOT AS INSTALL FROM ZIP by user preferences. Else, it gives different issues.
