### ISSUE TITLE
Error while importing a sketup model

### ISSUE THREAD

**Issue by MonkeyJLuffy** [arindam-m/pyslapi#68]
**Describe the bug**
I made a simple model and when I try to import it in my blender I have this error 

> Python : Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 1039, in execute
    return SceneImporter().set_filename(keywords['filepath']).load(
  File "C:\Users\Shadow\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 240, in load
    self.write_materials(self.skp_model.materials)
  File "C:\Users\Shadow\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 438, in write_materials
    default_shader = bmat.node_tree.nodes['Principled BSDF']
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

**To Reproduce**
1. Go to 'File>Inport'
2. Click on 'Sketchup files' and select your file

**Expected behavior**
The model imported

**Screenshots**
The model :
![image](https://github.com/arindam-m/pyslapi/assets/16681610/c34d62ad-6f3c-4252-9774-c33c08b46399)

**System Info**
 - Operating System:  Windows 10
 - Blender Version 4.0
 - SketchUp Version Pro 2023
 - Importer Version 0.23.2

**Comment by xiao6zide6** [comment]
SketchUp Pro 2022版
搅拌机版本4.0
导入程序版本0.23.2
window11同样出现了这个问题
错误代码
<img width="1920" alt="c99124cd7178ae7da38328debe7d566" src="https://github.com/arindam-m/pyslapi/assets/162530201/04a9a2ba-f48c-45af-9bd7-362eef0219b6">

bpy.ops.object.delete(use_global=False)
bpy.context.space_data.system_bookmarks_active = 1
Python: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 1039, in execute
    return SceneImporter().set_filename(keywords['filepath']).load(
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 240, in load
    self.write_materials(self.skp_model.materials)
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 438, in write_materials
    default_shader = bmat.node_tree.nodes['Principled BSDF']
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'
bpy.ops.import_scene.skp(filepath="C:\\Users\\ADMIN\\Desktop\\blender实验室\\无标题.skp")

**Comment by huafeishan** [comment]
SketchUp 2021版
搅拌机版本4.0
导入程序版本0.23.2
win10也出现了这个问题
![Snipaste_2024-03-23_10-39-35](https://github.com/arindam-m/pyslapi/assets/75918600/bf44898d-67d7-4679-bc95-efd7d4ce9a8b)
错误代码
bpy.ops.import_scene.skp(filepath="D:\\文档\\WeChat Files\\wxid_o8d98kamkp2i22\\FileStorage\\File\\2024-03\\1.skp", scenes_as_camera=True, reuse_material=True, max_instance=1)

**Comment by gvisual80** [comment]
> **Descrivi il bug** Ho realizzato un modello semplice e quando provo a importarlo nel mio frullatore ho questo errore
> 
> > Python: Traceback (ultima chiamata più recente): 
> > File "C:\Users\Shadow\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer_ _init_ _.py", riga 1039, nell'eseguire 
> > return SceneImporter() .set_filename(keywords['filepath']).load( 
> > File "C:\Users\Shadow\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer_ _init_ _.py", riga 240, nel caricamento 
> > self .write_materials(self.skp_model.materials) 
> > File "C:\Users\Shadow\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer_ _init_ _.py", riga 438, in write_materials 
> > default_shader = bmat.node_tree .nodes['Principled BSDF'] 
> > KeyError: 'bpy_prop_collection[key]: chiave "Principled BSDF" non trovata'
> 
> **Per riprodurre** Passaggi per riprodurre il comportamento:
> 
> 1. Vai su "File> Importa"
> 2. Fai clic su "File di sketch" e seleziona il tuo file
> 
> **Comportamento previsto** Il modello importato
>
> 
> **Informazioni sul sistema**
> 
> * Sistema operativo: Windows 10
> * Frullatore versione 4.1
> * Versione SketchUp Pro 2023
> * Versione importatore 0.23.2

![Senza titolo-1](https://github.com/arindam-m/pyslapi/assets/167925782/b7ec0a59-e4c1-4906-a9d0-84c54c154972)

anch'io ho lo stesso tipo di errore...

**Comment by MonkeyJLuffy** [comment]
I have a workaround.

In order to import SketchUp models to Blender, I have installed a previous version of Blender 3.x, I use the sketchup importer, then I save the blender file.

So, I can open it in Blender 4.x

**Comment by gvisual80** [comment]
Ho provato con 3.6 ma mi da lo stesso errore. Vorrei provare a scaricare il 3.2 ma non riesco a scaricare le versioni precedenti al 4.1...:-(
